from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DOC = ROOT / "docs" / "weekly-maintainer-loop.md"


def test_weekly_maintainer_loop_doc_has_required_sections():
    text = DOC.read_text(encoding="utf-8")

    required = [
        "# 每周维护者循环",
        "## 1. 周初：选一个可发布主题",
        "## 2. 周中：实现一个可验证切片",
        "## 3. 周末：发版或明确阻塞",
        "## 4. 周复盘问题",
        "python scripts/plan_next_iteration.py --json",
        "python scripts/plan_next_iteration.py --report",
        "python scripts/plan_next_iteration.py --issues-dir",
        "publication audit",
        "publication_visibility",
        "candidate_issue_gate",
        "blocked_by_publication",
        "review_required",
        "ready",
        "can_create_issues",
        "requires_maintainer_review",
        "required_actions",
        "evidence",
        "publication_ok",
        "publication_visibility_status",
        "publication_remote_checked",
        "publication_branch",
        "publication_latest_tag",
        "publication_ahead_count",
        "release_draft_issue_count",
        "published",
        "local_only",
        "dirty_worktree",
        "tag_not_visible",
        "needs_remote_check",
        "publication_next_actions",
        "publication_ref_context",
        "publication_worktree_clean",
        "publication_worktree_status",
        "publication_publish_commands",
        "publication_publish_script_command",
        "本地分支 ahead 数",
        "latest tag",
        "local HEAD",
        "tag commit",
        "branch/tag push",
        "python scripts/check_release_publication.py --remote --json",
        "--publish-script /tmp/cliany-publish-release.sh",
        "release_draft_issues",
        "release draft validation failed",
        "Candidate Issue Gate",
        "Candidate Issue Gate Evidence",
        "Candidate Promotion Tasks",
        "Candidate Issue Metadata",
        "Candidate Issue Body Templates",
        "Reproduction Context",
        "target URL",
        "candidate commands",
        "offline validation commands",
        "子列表",
        "审阅清单",
        "artifact-manifest.json",
        "issue-metadata.json",
        "publication-handoff.json",
        "release-draft-handoff.json",
        "publication next actions",
        "README.md",
        "Candidate Summary",
        "Publication Handoff",
        "candidate issue gate",
        "gate summary",
        "gate evidence latest tag",
        "gate evidence ahead count",
        "gate evidence release draft issues",
        "visibility",
        "visibility summary",
        "Publication Next Actions",
        "ref context",
        "worktree_clean",
        "worktree status",
        "Publication Publish Script",
        "Release Draft Handoff",
        "target version",
        "candidate count",
        "candidate cases",
        "blockers",
        "next actions",
        "candidate issue gate",
        "publication status",
        "publication visibility",
        "publication publish commands",
        "publication ref context",
        "publication worktree status",
        "publication publish script command",
        "release draft path",
        "release draft issues",
        "issue_artifacts_command",
        "schema_version",
        "review order",
        "validation commands",
        "python scripts/check_release_publication.py --json",
        "python scripts/release_readiness.py --target-version <version> --json",
        "review_checklist",
        "硬性 publication preflight",
        "gate 判定",
        "默认文本输出",
        "缩进列表",
        "release draft path",
        "release draft issues",
        "已处理或明确延后",
        "issue body 文件",
        "body file name",
        "body file path",
        "create-issues.sh",
        "publish commands",
        "python scripts/check_release_publication.py --strict --json",
        "/tmp/cliany-issue-publication-check.json",
        "如果 preflight 失败",
        "issue_artifacts_command",
        "复现命令",
        "/tmp/cliany-candidate-issues",
        "GitHub issue body",
        "issue title",
        "labels",
        "target URL",
        "adapter_package",
        "metadata_validation",
        "online_smoke",
        "python scripts/release_readiness.py --json",
        "python scripts/release_readiness.py --report",
        "Weekly Review",
        "python scripts/validate_cases.py --strict",
        "CLIANY_QA_OFFLINE=1 pytest tests/ -q --no-cov",
        "commit days N/3",
    ]
    for snippet in required:
        assert snippet in text


def test_weekly_maintainer_loop_referenced_paths_exist():
    text = DOC.read_text(encoding="utf-8")

    required_paths = [
        "docs/roadmap-2026-q3.md",
        "docs/release-cadence.md",
        "scripts/plan_next_iteration.py",
        "scripts/release_readiness.py",
        "scripts/validate_cases.py",
        "CHANGELOG.md",
    ]
    for path in required_paths:
        assert (ROOT / path).exists(), f"missing referenced path: {path}"
        assert path.split("/", 1)[-1] in text or path in text


def test_roadmap_and_release_cadence_link_weekly_loop():
    for path in (ROOT / "docs/roadmap-2026-q3.md", ROOT / "docs/release-cadence.md"):
        text = path.read_text(encoding="utf-8")
        assert "weekly-maintainer-loop.md" in text
