from __future__ import annotations

import json
import pathlib

import jsonschema
import pytest

from cliany_site.codegen.generator import METADATA_SCHEMA_VERSION, _build_minimal_smoke, save_adapter
from cliany_site.explorer.models import CommandSuggestion, ExploreResult

_MINIMAL_CODE = """\
# 自动生成 — DO NOT EDIT
# 生成时间: 2026-01-01T00:00:00+00:00
# 来源 URL: https://test.com
# 工作流: test-workflow

import click

@click.group()
def cli():
    pass

@cli.command("search")
def search():
    pass
"""

_SCHEMA_PATH = pathlib.Path("schemas/metadata.v2.json")


def _make_explore_result(command_names: list[str]) -> ExploreResult:
    commands = [
        CommandSuggestion(name=n, description=n, args=[], action_steps=[])
        for n in command_names
    ]
    return ExploreResult(commands=commands)


class TestMetadataSchemaVersion:
    def test_schema_version_is_int(self, tmp_home):
        save_adapter("test.com", _MINIMAL_CODE)
        meta_path = tmp_home / ".cliany-site" / "adapters" / "test.com" / "metadata.json"
        meta = json.loads(meta_path.read_text())
        assert meta["schema_version"] == 2
        assert isinstance(meta["schema_version"], int)

    def test_constant_is_integer_two(self):
        assert METADATA_SCHEMA_VERSION == 2
        assert isinstance(METADATA_SCHEMA_VERSION, int)


class TestV2FieldsPresent:
    def test_v2_fields_present(self, tmp_home):
        save_adapter("test.com", _MINIMAL_CODE)
        meta_path = tmp_home / ".cliany-site" / "adapters" / "test.com" / "metadata.json"
        meta = json.loads(meta_path.read_text())
        assert "canonical_actions" in meta
        assert "selector_pool" in meta
        assert "smoke" in meta
        assert "heal_history" in meta

    def test_v2_fields_are_lists(self, tmp_home):
        save_adapter("test.com", _MINIMAL_CODE)
        meta_path = tmp_home / ".cliany-site" / "adapters" / "test.com" / "metadata.json"
        meta = json.loads(meta_path.read_text())
        assert isinstance(meta["canonical_actions"], list)
        assert isinstance(meta["selector_pool"], list)
        assert isinstance(meta["smoke"], list)
        assert isinstance(meta["heal_history"], list)


class TestMetadataV2SchemaValid:
    def test_metadata_v2_schema_valid(self, tmp_home):
        schema = json.loads(_SCHEMA_PATH.read_text())
        explore_result = _make_explore_result(["search"])
        save_adapter("test.com", _MINIMAL_CODE, explore_result=explore_result)
        meta_path = tmp_home / ".cliany-site" / "adapters" / "test.com" / "metadata.json"
        meta = json.loads(meta_path.read_text())
        jsonschema.validate(meta, schema)


class TestSmokeAutoGenerated:
    def test_smoke_length_matches_commands(self, tmp_home):
        explore_result = _make_explore_result(["search", "login"])
        save_adapter("test.com", _MINIMAL_CODE, explore_result=explore_result)
        meta_path = tmp_home / ".cliany-site" / "adapters" / "test.com" / "metadata.json"
        meta = json.loads(meta_path.read_text())
        assert len(meta["smoke"]) == 2

    def test_smoke_capped_at_three(self, tmp_home):
        explore_result = _make_explore_result(["a", "b", "c", "d", "e"])
        save_adapter("test.com", _MINIMAL_CODE, explore_result=explore_result)
        meta_path = tmp_home / ".cliany-site" / "adapters" / "test.com" / "metadata.json"
        meta = json.loads(meta_path.read_text())
        assert len(meta["smoke"]) == 3

    def test_smoke_contains_command_name(self, tmp_home):
        explore_result = _make_explore_result(["do-search"])
        save_adapter("test.com", _MINIMAL_CODE, explore_result=explore_result)
        meta_path = tmp_home / ".cliany-site" / "adapters" / "test.com" / "metadata.json"
        meta = json.loads(meta_path.read_text())
        assert meta["smoke"][0]["command"] == "do-search"
        assert meta["smoke"][0]["args"] == {}
        assert meta["smoke"][0]["expect"] == {"ok": True}


class TestBuildMinimalSmoke:
    def test_empty_commands(self):
        assert _build_minimal_smoke([]) == []

    def test_two_commands(self):
        result = _build_minimal_smoke([{"name": "a"}, {"name": "b"}])
        assert len(result) == 2
        assert result[0]["command"] == "a"
        assert result[1]["command"] == "b"

    def test_missing_name_defaults_empty(self):
        result = _build_minimal_smoke([{}])
        assert result[0]["command"] == ""
