from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DOC = ROOT / "docs" / "weekly-maintainer-loop.md"


def test_weekly_maintainer_loop_doc_has_required_sections():
    text = DOC.read_text(encoding="utf-8")

    required = [
        "# 每周维护者循环",
        "## 1. 周初：选一个可发布主题",
        "## 2. 周中：实现一个可验证切片",
        "## 3. 周末：发版或明确阻塞",
        "## 4. 周复盘问题",
        "python scripts/plan_next_iteration.py --json",
        "python scripts/plan_next_iteration.py --report",
        "python scripts/plan_next_iteration.py --issues-dir",
        "publication audit",
        "publication_visibility",
        "candidate_issue_gate",
        "blocked_by_publication",
        "review_required",
        "ready",
        "can_create_issues",
        "requires_maintainer_review",
        "reason_codes",
        "reason_descriptions",
        "human-readable",
        "可读说明",
        "required_actions",
        "Resolve release draft issue",
        "required_action_count",
        "required_actions_sha256",
        "required actions hash",
        "reason_code_count",
        "reason_codes_sha256",
        "reason codes hash",
        "candidate_issue_gate_key_count",
        "candidate_issue_gate_sha256",
        "candidate_issue_gate_reason_description_count",
        "candidate_issue_gate_reason_descriptions_sha256",
        "candidate_issue_gate_reason_code_count",
        "candidate_issue_gate_reason_codes_sha256",
        "candidate_issue_gate_primary_reason_code",
        "candidate_issue_gate_primary_reason_description",
        "candidate_issue_gate_required_action_count",
        "candidate_issue_gate_required_actions_sha256",
        "candidate_issue_gate_primary_required_action",
        "Candidate Issue Gate Quick Summary",
        "publication/release draft ok",
        "blocker/next action 数量",
        "publication publish command 数量",
        "publication publish script path",
        "publication publish script command",
        "reason/action 数量",
        "publication branch/upstream/remote",
        "publication local HEAD/tag commit/upstream HEAD",
        "publication tag state",
        "publication published state",
        "publication remote refs",
        "publication worktree clean",
        "publication ahead/behind 数",
        "publication remote checked",
        "release draft issue 数",
        "release draft path",
        "visibility summary",
        "publication_visibility_status",
        "publication_remote_checked",
        "publication_ahead_count",
        "publication_behind_count",
        "publication_branch",
        "publication_upstream",
        "publication_remote",
        "publication_latest_tag",
        "publication_tag_commit",
        "publication_local_head",
        "publication_upstream_head",
        "publication_tag_points_at_head",
        "publication_tag_commit_in_upstream",
        "publication_branch_published",
        "publication_tag_published",
        "publication_remote_branch_head",
        "publication_remote_tag_commit",
        "publication_ok",
        "release_draft_ok",
        "release_draft_issue_count",
        "candidate_issue_gate_summary_sha256",
        "candidate_issue_gate_evidence_key_count",
        "candidate_issue_gate_evidence_sha256",
        "blocker_count",
        "next_action_count",
        "publication_next_action_count",
        "publication_publish_command_count",
        "publication_publish_script_path",
        "publication_publish_script_path_sha256",
        "publication_publish_script_command",
        "publication_publish_script_command_sha256",
        "blockers_sha256",
        "next_actions_sha256",
        "publication_next_actions_sha256",
        "publication_primary_next_action",
        "publication_handoff_key_count",
        "publication_handoff_schema_version",
        "publication_handoff_sha256",
        "publication_ref_context_key_count",
        "publication_ref_context_sha256",
        "publication_publish_command_count",
        "publication_publish_commands_sha256",
        "publication_primary_publish_command",
        "publication_worktree_status_count",
        "publication_worktree_status_sha256",
        "release_draft_handoff_key_count",
        "release_draft_handoff_schema_version",
        "release_draft_handoff_primary_issue",
        "release_draft_handoff_primary_required_action",
        "release_draft_handoff_sha256",
        "release_draft_path",
        "release_draft_path_sha256",
        "release_draft_primary_issue",
        "primary_issue",
        "release_draft_required_action_count",
        "release_draft_required_actions_sha256",
        "release_draft_primary_required_action",
        "primary_required_action",
        "release_draft_issues_sha256",
        "validation_command_count",
        "validation_commands_sha256",
        "review_checklist_count",
        "review_checklist_sha256",
        "create_issues_safety_contract_key_count",
        "create_issues_safety_contract_sha256",
        "dry-run/preflight 契约",
        "evidence",
        "publication_ok",
        "publication_visibility_status",
        "publication_worktree_clean",
        "publication_remote_checked",
        "publication_branch",
        "publication_latest_tag",
        "publication_ahead_count",
        "release_draft_ok",
        "release_draft_issue_count",
        "publication_not_published",
        "local_release_only",
        "published",
        "local_only",
        "dirty_worktree",
        "tag_not_visible",
        "needs_remote_check",
        "publication_next_actions",
        "publication_ref_context",
        "publication_worktree_clean",
        "publication_worktree_status",
        "publication_publish_commands",
        "publication_publish_script_path",
        "publication publish script path hash",
        "publication publish script command hash",
        "publication_publish_script_command",
        "本地分支 ahead 数",
        "latest tag",
        "local HEAD",
        "tag commit",
        "branch/tag push",
        "python scripts/check_release_publication.py --remote --json",
        "--publish-script /tmp/cliany-publish-release.sh",
        "release_draft_issues",
        "release draft validation failed",
        "Candidate Issue Gate",
        "Candidate Issue Gate Reason Codes",
        "Candidate Issue Gate Reason Descriptions",
        "Candidate Issue Gate Evidence",
        "Candidate Promotion Tasks",
        "Candidate Issue Metadata",
        "Candidate Issue Body Templates",
        "Reproduction Context",
        "target URL",
        "candidate commands",
        "offline validation commands",
        "子列表",
        "审阅清单",
        "artifact-manifest.json",
        "issue-metadata.json",
        "publication-handoff.json",
        "release-draft-handoff.json",
        "publication next actions",
        "README.md",
        "Candidate Summary",
        "Publication Handoff",
        "candidate issue gate",
        "gate summary",
        "gate reason codes",
        "gate reason descriptions",
        "gate evidence latest tag",
        "gate evidence ahead count",
        "gate evidence worktree clean",
        "gate evidence release draft ok",
        "gate evidence release draft issues",
        "visibility",
        "visibility summary",
        "Publication Next Actions",
        "primary_next_action",
        "ref context",
        "worktree_clean",
        "worktree status",
        "Publication Publish Script",
        "publish_command_count",
        "primary_publish_command",
        "publish_script_path",
        "publish_script_path_sha256",
        "publish_script_command_sha256",
        "Create Issues Safety",
        "dry_run_supported",
        "dry_run_env",
        "dry_run_command",
        "preflight_required",
        "preflight_command",
        "preflight_json",
        "Release Draft Handoff",
        "schema_version",
        "release_draft_ok",
        "release_draft_issue_count",
        "release_draft_primary_issue",
        "primary_issue",
        "release_draft_primary_required_action",
        "primary_required_action",
        "release_draft_required_action_count",
        "release_draft_required_actions_sha256",
        "release_draft_required_actions",
        "release_draft_path_sha256",
        "release_draft_issues_sha256",
        "target version",
        "candidate count",
        "candidate cases",
        "blockers",
        "next actions",
        "candidate issue gate",
        "publication status",
        "publication visibility",
        "publication publish commands",
        "publication ref context",
        "publication worktree status",
        "publication publish script command",
        "publication_publish_script_command_sha256",
        "publication_publish_script_path_sha256",
        "release draft path",
        "release draft issues",
        "issue_artifacts_command",
        "schema_version",
        "review order",
        "validation commands",
        "create_issues_dry_run_command",
        "create_issues_safety",
        "issue_body_inventory",
        "issue_body_summary",
        "artifact_bundle_summary",
        "artifact_bundle_summary_key_count",
        "artifact_bundle_summary_keys_sha256",
        "artifact_bundle_summary_key_preview_count",
        "artifact_bundle_summary_key_preview",
        "artifact_bundle_summary_key_preview_sha256",
        "artifact_bundle_summary_key_tail_count",
        "artifact_bundle_summary_key_tail",
        "artifact_bundle_summary_key_tail_sha256",
        "artifact_bundle_summary_first_key",
        "artifact_bundle_summary_last_key",
        "artifact_bundle_summary_key_boundary_sha256",
        "artifact_manifest_first_key",
        "artifact_manifest_last_key",
        "artifact_manifest_key_boundary_sha256",
        "artifact_manifest_key_preview_count",
        "artifact_manifest_key_preview",
        "artifact_manifest_key_preview_sha256",
        "artifact_manifest_key_tail_count",
        "artifact_manifest_key_tail",
        "artifact_manifest_key_tail_sha256",
        "artifact_manifest_schema_version",
        "artifact_manifest_key_count",
        "artifact_manifest_keys_sha256",
        "artifact_manifest_payload_key_count",
        "artifact_manifest_payload_first_key",
        "artifact_manifest_payload_last_key",
        "artifact_manifest_payload_key_boundary_sha256",
        "artifact_manifest_payload_key_preview_count",
        "artifact_manifest_payload_key_preview",
        "artifact_manifest_payload_key_preview_sha256",
        "artifact_manifest_payload_key_tail_count",
        "artifact_manifest_payload_key_tail",
        "artifact_manifest_payload_key_tail_sha256",
        "artifact_manifest_payload_sha256",
        "review_order_sha256",
        "review order hash",
        "candidate_cases_first_case",
        "candidate_cases_last_case",
        "candidate_cases_boundary_sha256",
        "candidate_cases_preview_count",
        "candidate_cases_preview",
        "candidate_cases_preview_sha256",
        "candidate_cases_tail_count",
        "candidate_cases_tail",
        "candidate_cases_tail_sha256",
        "candidate_cases_sha256",
        "issue_body_inventory_preview_count",
        "issue_body_inventory_preview",
        "issue_body_inventory_preview_sha256",
        "issue_body_inventory_first_entry",
        "issue_body_inventory_last_entry",
        "issue_body_inventory_boundary_sha256",
        "issue_body_inventory_tail_count",
        "issue_body_inventory_tail",
        "issue_body_inventory_tail_sha256",
        "issue_body_summary_key_count",
        "issue_body_summary_keys_sha256",
        "issue_body_summary_first_key",
        "issue_body_summary_last_key",
        "issue_body_summary_key_boundary_sha256",
        "issue_body_summary_sha256",
        "issue_metadata_count",
        "issue_metadata_sha256",
        "不包含本机输出路径",
        "artifact_files_key_count",
        "artifact_files_sha256",
        "issue_artifacts_command_sha256",
        "publication_visibility_key_count",
        "publication_visibility_sha256",
        "publication_visibility_summary_sha256",
        "byte_count",
        "sha256",
        "body_count",
        "total_byte_count",
        "inventory_sha256",
        "review_item_count",
        "candidate_issue_gate_status",
        "python scripts/check_release_publication.py --json",
        "python scripts/release_readiness.py --target-version <version> --json",
        "artifact-manifest.json.validation_commands",
        "Validation Commands",
        "plan_next_iteration.py --json",
        "check_release_publication.py --json",
        "validate_cases.py --strict",
        "publication audit",
        "publish_command_count",
        "review_checklist",
        "硬性 publication preflight",
        "gate 判定",
        "默认文本输出",
        "缩进列表",
        "仓库相对路径",
        "docs/releases/v<version>-draft.md",
        "release draft path",
        "release draft issues",
        "已处理或明确延后",
        "issue body 文件",
        "body file name",
        "body file path",
        "Issue Body Inventory",
        "Issue Body Summary",
        "Artifact Bundle Summary",
        "SHA-256",
        "create-issues.sh",
        "CLIANY_CREATE_ISSUES_DRY_RUN=1 ./create-issues.sh",
        "dry-run mode",
        "不创建 issue",
        "publish commands",
        "python scripts/check_release_publication.py --strict --json",
        "/tmp/cliany-issue-publication-check.json",
        "如果 preflight 失败",
        "issue_artifacts_command",
        "复现命令",
        "/tmp/cliany-candidate-issues",
        "GitHub issue body",
        "issue title",
        "labels",
        "target URL",
        "adapter_package",
        "metadata_validation",
        "online_smoke",
        "python scripts/release_readiness.py --json",
        "python scripts/release_readiness.py --report",
        "Weekly Review",
        "python scripts/validate_cases.py --strict",
        "CLIANY_QA_OFFLINE=1 pytest tests/ -q --no-cov",
        "commit days N/3",
    ]
    for snippet in required:
        assert snippet in text


def test_weekly_maintainer_loop_referenced_paths_exist():
    text = DOC.read_text(encoding="utf-8")

    required_paths = [
        "docs/roadmap-2026-q3.md",
        "docs/release-cadence.md",
        "scripts/plan_next_iteration.py",
        "scripts/release_readiness.py",
        "scripts/validate_cases.py",
        "CHANGELOG.md",
    ]
    for path in required_paths:
        assert (ROOT / path).exists(), f"missing referenced path: {path}"
        assert path.split("/", 1)[-1] in text or path in text


def test_roadmap_and_release_cadence_link_weekly_loop():
    for path in (ROOT / "docs/roadmap-2026-q3.md", ROOT / "docs/release-cadence.md"):
        text = path.read_text(encoding="utf-8")
        assert "weekly-maintainer-loop.md" in text
